# **Day-12 Coding Practice**

In [1]:
import numpy as np

1. **Create a NumPy array of numbers from 1 to 16.**  
**Reshape it into a 4x4 matrix.**  
**Then:**  
  
- **Print the matrix.**
- **Print the sum of each column.**
- **Print the sum of each row.**
- **Print the difference between row-wise sum and column-wise sum.**
- **Print the shape after applying sum(axis=0).**

In [14]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
b=a.reshape(4, 4)
row=b.sum(axis=1)
col=b.sum(axis=0)
print("\nMatrix is", b)
print("\nSum of each column is: ", col)
print("\nSum of each row is: ", row)
print("\nDifference between sum of row and column is: ", row-col)
print("\nShape of column wise sum is: ", col.shape)


Matrix is [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sum of each column is:  [28 32 36 40]

Sum of each row is:  [10 26 42 58]

Difference between sum of row and column is:  [-18  -6   6  18]

Shape of column wise sum is:  (4,)


2. **Using the same 4x4 matrix:**  

- **Extract the second row.**
- **Extract the third column.**
- **Extract the top-left 2x2 sub-matrix.**
- **Extract the bottom-right 2x2 sub-matrix.**
- **Extract all elements greater than 10.**


In [15]:
print(b[1])
print(b[:, 2])
print(b[0:2, 0:2])
print(b[2:4, 2:4])
print(b[b>10])

[5 6 7 8]
[ 3  7 11 15]
[[1 2]
 [5 6]]
[[11 12]
 [15 16]]
[11 12 13 14 15 16]


3. **Using the same 4x4 matrix:**  

- **Replace all even numbers with -1.**
- **Replace all numbers divisible by 3 with 0.**
- **Count how many numbers are greater than 8.**
- **Find the positions (row, column) of numbers greater than 12.**


In [16]:
modify=b.copy()
modify[modify%2==0]=-1
print("\nThe modified matrix is: ", modify)
modify[modify%3==0]=0
print("\nThe modified matrix is: ", modify)
count=np.sum(modify>8)
print("\nThe total number of elements greater then 8 are: ", count)
positions=np.where(b>12)
cords=list(zip(positions[0], positions[1]))
print("\nPositions", cords)


The modified matrix is:  [[ 1 -1  3 -1]
 [ 5 -1  7 -1]
 [ 9 -1 11 -1]
 [13 -1 15 -1]]

The modified matrix is:  [[ 1 -1  0 -1]
 [ 5 -1  7 -1]
 [ 0 -1 11 -1]
 [13 -1  0 -1]]

The total number of elements greater then 8 are:  2

Positions [(np.int64(3), np.int64(0)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(3), np.int64(3))]
