# **Day-12 Coding Practice**

In [1]:
import numpy as np

1. **Create a NumPy array from 1 to 24.**  
**Reshape it into a 4x6 matrix.**  
**Then:**  
- **Print the matrix.**
- **Print the mean of each column.**
- **Print the mean of each row.**
- **Print the shape after applying mean(axis=0).**
- **Print the shape after applying mean(axis=1).**


In [2]:
a=np.arange(1, 25)
b=a.reshape(4, 6)
print("\nThe matrix is: \n", b)
row=b.mean(axis=1)
col=b.mean(axis=0)
print("\nThe mean of each column is: \n", col)
print("\nThe mean of each row is: \n", row)
print("\nThe shape of mean(axis=0) is: \n", col.shape)
print("\nThe shape of mean(axis=1) is: \n", row.shape)


The matrix is: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

The mean of each column is: 
 [10. 11. 12. 13. 14. 15.]

The mean of each row is: 
 [ 3.5  9.5 15.5 21.5]

The shape of mean(axis=0) is: 
 (6,)

The shape of mean(axis=1) is: 
 (4,)


2. **Using the same 4x6 matrix:**  
- **Add 10 to every element.**
- **Create a 1D array of length 6 (e.g., [1,2,3,4,5,6]).**
- **Add that 1D array to the matrix.**

In [4]:
modify=b.copy()
modify=modify+10
r=np.arange(1, 7)
modify=modify+r
print(modify)


[[12 14 16 18 20 22]
 [18 20 22 24 26 28]
 [24 26 28 30 32 34]
 [30 32 34 36 38 40]]


3. **Using the same 4x6 matrix:**
  
- **Find all elements divisible by 5.**
- **Print their positions (row, column).**
- **Count how many such elements exist.**
- **Replace those elements with -99.**
- **Print the modified matrix.**


In [5]:
mask=b%5==0
print("\nElements divisble by 5 are: \n", b[mask])
positions=np.where(mask)
coords=list(zip(positions[0], positions[1]))
print("\nThe coordinates of such elements are: \n", coords)
count=np.sum(mask)
print("\nNumber of such elements are: ", count)
b[mask]=-99
print("\nThe modified matrix is: \n", b)


Elements divisble by 5 are: 
 [ 5 10 15 20]

The coordinates of such elements are: 
 [(np.int64(0), np.int64(4)), (np.int64(1), np.int64(3)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(1))]

Number of such elements are:  4

The modified matrix is: 
 [[  1   2   3   4 -99   6]
 [  7   8   9 -99  11  12]
 [ 13  14 -99  16  17  18]
 [ 19 -99  21  22  23  24]]
