# **Day-11 Coding Practice**

In [1]:
import numpy as np

1. **Create a NumPy array containing numbers from 1 to 10.**   
**Then:**  
- **Print the array.**  
- **Print its shape.**  
- **Print its size.**  
- **Print its data type.**  
- **Print the element at index 4.** 


In [23]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
print(a.shape)
print(a.size)
print(type(a))
print(a[4])

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
10
<class 'numpy.ndarray'>
5


2. **Using the same numbers from 1 to 10, create a new NumPy array.**  
**Reshape it into a 2x5 matrix.**  
**Then:**  
- **Print the matrix.**
- **Print the first row.**
- **Print the last column.**
- **Print the element at row 1, column 3.**


In [24]:
b=a.reshape(2, 5)
print(b)
print(b[1])
print(b[:,-1])
print(b[1:,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
[ 5 10]
[9]


3. **Using the 2x5 matrix from Problem 2:**  

- **Add 5 to every element in the matrix.**
- **Multiply every element by 2.**
- **Find the sum of all elements.**
- **Find the sum of elements column-wise.**
- **Find the mean of all elements.**


In [20]:
print(b+5)
print(b*2)
print(b.sum())
print(b.sum(axis=0))
print(b.mean())

[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
55
[ 7  9 11 13 15]
5.5


4. **Using the same 2x5 matrix:**

- **Print all elements greater than 5.**
- **Replace all even numbers with 0.**
- **Count how many numbers are greater than the mean.**
- **Find the maximum value**


In [21]:
print("\nCurrent matrix is: ", b)
print("\nElements greater then 5 are: ", b[b>5])
modify=b
modify[modify%2==0]=0
print("\nModified matrix with replaced elements is: ", modify)
mean=b.mean()
count=np.sum(b>mean)
print("\nNumber of values greater then mean value are", count)
print("\nMaximum value in the given matrix is", b.max())


Current matrix is:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Elements greater then 5 are:  [ 6  7  8  9 10]

Modified matrix with replaced elements is:  [[1 0 3 0 5]
 [0 7 0 9 0]]

Number of values greater then mean value are 4

Maximum value in the given matrix is 9
